### ISSUE TITLE
Styling improvements for default theme

### ISSUE THREAD

**Issue by ajb** [dobtco/dispatch#17]
I assume that @jrubenoff can go through the app and find a bunch of things to fix that aren't visible to me as a non-designer.
- CSS should be added to `themes/dvl-core/assets/stylesheets/themes/`
- Templates should be edited in `app/views/`

**Comment by ajb** [comment]
I should add: the area that's in most need of help IMO is the Q&A:

![img](http://take.ms/uNNYP)

**Comment by jrubenoff** [comment]
Broken out into separate issues
