### ISSUE TITLE
Separate i18n for name / email / password fields

### ISSUE THREAD

**Issue by jrubenoff** [dobtco/dispatch#22]
I need to be able to specify separate i18n for these pages, even though they have the same fields:
- Vendor signup
- Staff signup
- Sign in
- Account page

The desired tone of language needs to be different for the onboarding process than other pages. (For example, "What's your email address?" vs. "Email".)

Since the signup form for vendors is twice as long as that for government staff, it would be great to have separate i18n for each of those forms as well.

**Comment by ajb** [comment]
Just use inline translations instead of the `simple_form` magic:

``` erb
<%= simple_form_for resource, as: resource_name, url: session_path(resource_name) do |f| %>
  <%= f.input :email, required: false, autofocus: true, label: t('whats_your_email') %>
  <%= f.input :password, required: false, label: t('password'), hint: t('make_it_8_chars') %>
```

**Comment by jrubenoff** [comment]
Done in `polish`
