### ISSUE TITLE
Show number of results for a filter

### ISSUE THREAD

**Issue by jrubenoff** [dobtco/dispatch#25]
When a user is filtering a response, we should show them the number of matching search results.

![screen shot 2016-04-27 at 12 06 57 am](https://cloud.githubusercontent.com/assets/1328849/14844407/0af791c6-0c0c-11e6-8761-53475c33fd9d.png)

**Comment by jrubenoff** [comment]
Not quite done. Can we remove the count (and / or change the i18n from `%{n} search results` to `%{n} opportunities`) when no filters have been applied yet?

(This is non-urgent.)

**Comment by ajb** [comment]
I was assuming that this can be discussed in the PR, especially since it still needs styling?

You can do this yourself; it will take a second. Use the `filtered?` helper to conditionally change the i18n key. I think that we should definitely display the # of results when there are no filters.

**Comment by jrubenoff** [comment]
Done, thanks!
