### ISSUE TITLE
Remove title step in wizard

### ISSUE THREAD

**Issue by jrubenoff** [dobtco/dispatch#26]
`opportunities/new/` and `/opportunities/edit/title` are two different pages with exactly the same content. They shouldn't both exist.

One idea: We remove the title page from the wizard, and add a Rename button to the wizard's page header. This would summon a Rename modal, like in Screendoor.

![screen shot 2016-04-27 at 12 11 29 am](https://cloud.githubusercontent.com/assets/1328849/14844493/9eb03bfc-0c0c-11e6-92c8-f228a3ffcce8.png)

**Comment by ajb** [comment]
I'm trying to avoid adding any complex JavaScript (like modals) because it would hamper the customizability of this repo. 

I'd be OK with displaying a text input inline, even though that's a little more JS-y than I originally wanted. Does that work?

**Comment by ajb** [comment]
Anticipating your answer, I went ahead and did the inline input thing :)

It's in the `polish` branch, and probably needs some polish.
