### ISSUE TITLE
Design list of saved searches

### ISSUE THREAD

**Issue by jrubenoff** [dobtco/dispatch#30]

**Comment by ajb** [comment]
Consolidating w/ #21. The design is totally 👌 for now.

**Comment by jrubenoff** [comment]
Actually, there are some legibility issues here that need fixing.

**Comment by ajb** [comment]
Can you clarify? How is this separate from #21?

**Comment by ajb** [comment]
Next time, please expound on this... there were some issues with the redesigned component that I documented in #48.
