### ISSUE TITLE
Fix awkward sidebar on opportunity page

### ISSUE THREAD

**Issue by jrubenoff** [dobtco/dispatch#31]
![screen shot 2016-04-27 at 12 14 35 am](https://cloud.githubusercontent.com/assets/1328849/14844560/09f53156-0c0d-11e6-98d3-f22f37d7b053.png)

**Comment by ajb** [comment]
:+1:

Also:

![img](http://take.ms/lACNp)

**Comment by ajb** [comment]
Is this done? If not, what is outstanding?

**Comment by ajb** [comment]
Again, an (brief) explanation would be appreciated for documentation's sake.
