### ISSUE TITLE
Deleting an opportunity from the Approval page should take you back to that page

### ISSUE THREAD

**Issue by jrubenoff** [dobtco/dispatch#44]
### Steps to Reproduce
1. Click on an opportunity in the Approve page.
2. Delete it.
3. The user is taken back to the homepage.
### Expected Behavior

In Step 3, the user should return to the Approve page, so they can continue reviewing submissions.

**Comment by ajb** [comment]
OK. If the user has the ability to view the "Approve" page, the destroy action will redirect there. If a user deletes their own opportunity and does not have permission to view the "Approve" page, they'll still be redirected to the home page.
