### ISSUE TITLE
Better saving behavior in the wizard

### ISSUE THREAD

**Issue by jrubenoff** [dobtco/dispatch#45]
The "Save and continue" button in the wizard is very confusing. I usually find myself clicking another tab and forgetting that my work didn't actually save.

At the very least, we should have a `beforeUnload` alert if the user clicks another link, asking them whether they want to discard their changes.

**Comment by ajb** [comment]
:+1:

Will add beforeunload.

**Comment by ajb** [comment]
By the way, I'm also happy to implement other solutions... I just don't know what else to do unless you suggest it.
