### ISSUE TITLE
Validate for agency email addresses in vendor signup

### ISSUE THREAD

**Issue by jrubenoff** [dobtco/dispatch#46]
### Outcome

Help alert government staff if they accidentally sign up as a vendor.
### Structure

It would be nice if we could validate client-side for agency email addresses as they're typed in, and display an alert accordingly:

![screen shot 2016-04-29 at 4 10 02 pm](https://cloud.githubusercontent.com/assets/1328849/14931961/e578ac9e-0e24-11e6-9059-f01151209fc0.png)

**Comment by ajb** [comment]
If a government employee signs up thru the vendor form, they'll still be granted the correct permissions.
