### ISSUE TITLE
Approve page looks funky when there's a header on one section only

### ISSUE THREAD

**Issue by ajb** [dobtco/dispatch#52]

**Comment by ajb** [comment]
![img](http://take.ms/myPSz)

**Comment by jrubenoff** [comment]
I disagree, but to broaden this a bit, I'm also not sure why the "pending" section is on this page. It's not totally intuitive to visit the "Approve" page to see opportunities that have already been approved.

What if we removed this section, and staff were able to see (and filter for) pending opportunities on the Browse page?

**Comment by ajb** [comment]
Seems like a good idea. Will create a new issue and close this one.
